server:
    port: 9081
    context-path: /api
    session:
        cookie:
            name: API_SESSION

security:
    user:
        password: none
    oauth2:
        client:
            accessTokenUri: https://auth-dev.46.249.93.103.nip.io/oauth/token
            userAuthorizationUri: https://auth-dev.46.249.93.103.nip.io/oauth/authorize
            clientId: Challenge Me
            clientSecret: challengeMeSecret
        resource:
            jwt:
                key-uri: https://auth-dev.46.249.93.103.nip.io/oauth/token_key